# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 

trigger:
- none

pool:
  name: 'Azure Pipelines'

variables:
  azureServiceConnection: 'Azure DevOps'
  location: 'westeurope'
  resourceGroupName: 'debont-test-rg'
  storageAccountName: 'subariosstorage12345'
  templateFile: './learning/Tutorial1.bicep'

stages: 
- stage: 'pre_test'
  displayName: 'Pre-deployment Tests'
  jobs: 
  - job: PreDeploymentTests
    displayName:  'Pre-deployment Tests'
    steps:
    - task: AzurePowerShell@5
      displayName: "Run Pre-deployement tests"
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptType: "Inlinescript"
        Inline: |
           Set-Location ./pre-tests
           Invoke-Pester -CI -Output Detailed
        pwsh: true   
        azurePowershellVersion: 'LatestVersion'


- stage: DeployStorageAccount
  displayName: 'Deploy Storage Account'
  jobs:
  - job: DeployStorageAccount
    steps:
    - task: AzureResourceManagerTemplateDeployment@3 # more info: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines
      displayName: 'Tutorial 1'
      inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '$(azureServiceConnection)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourcegroupName)'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: '$(templateFile)'
          overrideParameters: ''
          deploymentMode: 'Incremental'
          deploymentName: 'Tutorial1'



- stage: 'post_test'
  displayName: 'Post-deployment Tests'
  jobs: 
  - job: PostDeploymentTests
    displayName:  'Post-deployment Tests'
    steps:
    - task: AzurePowerShell@5
      displayName: "Run Post-deployement tests"
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptType: "Inlinescript"
        Inline: |
           Set-Location ./post-tests
           Invoke-Pester -CI
        pwsh: 'true'   
        azurePowershellVersion: 'LatestVersion'

#    - task: PublishTestResults@2
#      inputs:
#          testResultsFormat: "NUnit"
#          testResultsFiles: "**/Test*.xml"
#          failTaskOnFailedTests: true
#          testRunTitle: "Validate Task Files"
