# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 

trigger:
- none

pool:
  name: 'Host Pool'

variables:
  azureServiceConnection: 'Azure DevOps'
  location: westeurope
  resourcegroup: debont-test-rg
  templateFile: './learning/Tutorial1.bicep'

steps:
- bash: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: 'Install AzureCLI'

- bash: sudo snap install powershell --classic
  displayName: 'Install Powershell'

- task: AzureResourceManagerTemplateDeployment@3 # more info: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines
  displayName: 'Tutorial 1'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourcegroup)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    overrideParameters: ''
    deploymentMode: 'Incremental'
    deploymentName: 'Tutorial1'
