trigger:
- none

pool:
  name: 'Host Pool - Linux'
 
parameters:
 - name: envs # collection of environments to create/deploy
   type: object
   default:
      env:
        name: ''
        branches: []


variables:
  subscription: Rubicon-MPN
  location: westeurope

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

